### ISSUE TITLE
Strict Standards

### ISSUE THREAD

**Issue by lifecom** [kpoxas/tagextender#1]
Strict Standards: Declaration of PluginTagskit_ModuleTopic_MapperTopic::GetOpenTopicTags() should be compatible with PluginTagextender_ModuleTopic_MapperTopic::GetOpenTopicTags($iLimit, $iUserId = NULL, $aGroupId = Array) in /plugins/tagskit/classes/modules/topic/mapper/Topic.mapper.class.php on line 4

**Comment by kpoxas** [comment]
В вашем плагине либо пропишите те же параметры у метода PluginTagskit_ModuleTopic_MapperTopic::GetOpenTopicTags(), что и у моего плагина

```
PluginTagextender_ModuleTopic_MapperTopic::GetOpenTopicTags($iLimit, $iUserId = NULL, $aGroupId = Array)
```

либо поменяйте в plugins.dat порядок запуска плагинов, чтобы ваш инициализировался раньше, тогда надо параметры метода прописывать, как у нативного  метода  ModuleTopic_MapperTopic
